export default {
  id: "alicode",
  priority: 20,
  alias: "alicode",
  display: {
    name: "Alibaba",
    icon: "cloud",
    color: "#FF6A00",
    textIcon: "ALi",
    website: "https://bailian.console.aliyun.com",
    notice: {
      apiKeyUrl: "https://bailian.console.aliyun.com/?apiKey=1",
    },
  },
  category: "apikey",
  hasFree: true,
  transport: {
    baseUrl: "https://coding.dashscope.aliyuncs.com/v1/chat/completions",
    headers: {},
    quirks: { preserveCacheControl: true },
  },
  models: [
    { id: "qwen3.8-max-preview", name: "Qwen 3.8 Max Preview" },
    { id: "qwen3.7-max", name: "Qwen 3.7 Max" },
    { id: "qwen3.7-plus", name: "Qwen 3.7 Plus" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus" },
    { id: "qwen3.5-plus", name: "Qwen 3.5 Plus" },
    { id: "qwen-max-latest", name: "Qwen Max Latest" },
    { id: "qwen-plus-latest", name: "Qwen Plus Latest" },
    { id: "qwen-turbo-latest", name: "Qwen Turbo Latest" },
    { id: "qwen2.5-coder-32b-instruct", name: "Qwen 2.5 Coder 32B" },
    { id: "qwen2.5-72b-instruct", name: "Qwen 2.5 72B" },
    { id: "qwq-32b-preview", name: "QwQ 32B Preview", supportsReasoning: true },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5", name: "GLM 5" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "qwen3-max-2026-01-23", name: "Qwen3 Max" },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "glm-4.7", name: "GLM 4.7" },
  ],
  passthroughModels: true,
};
