export default {
  id: "anthropic",
  priority: 30,
  alias: "anthropic",
  display: {
    name: "Anthropic",
    icon: "smart_toy",
    color: "#D97757",
    textIcon: "AN",
    website: "https://console.anthropic.com",
    notice: {
      apiKeyUrl: "https://console.anthropic.com/settings/keys",
    },
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.anthropic.com/v1/messages",
    format: "claude",
    headers: {
      "anthropic-version": "2023-06-01",
      "Anthropic-Beta": "claude-code-20250219,interleaved-thinking-2025-05-14",
    },
  },
  models: [
    { id: "claude-3-7-sonnet-20250219", name: "Claude 3.7 Sonnet (20250219)", contextLength: 200000 },
    { id: "claude-3-7-sonnet", name: "Claude 3.7 Sonnet", contextLength: 200000 },
    { id: "claude-3-5-sonnet-20241022", name: "Claude 3.5 Sonnet", contextLength: 200000 },
    { id: "claude-3-5-haiku-20241022", name: "Claude 3.5 Haiku", contextLength: 200000 },
    { id: "claude-3-opus-20240229", name: "Claude 3 Opus", contextLength: 200000 },
    { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4" },
    { id: "claude-opus-4-20250514", name: "Claude Opus 4" },
    { id: "claude-fable-5", name: "Claude Fable 5", contextLength: 1048576, unsupportedParams: ["temperature", "top_p", "top_k"] },
    { id: "claude-opus-5", name: "Claude Opus 5", contextLength: 1000000, maxOutputTokens: 128000, supportsXHighEffort: true, unsupportedParams: ["temperature", "top_p", "top_k"] },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7", unsupportedParams: ["temperature", "top_p", "top_k"] },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8", contextLength: 1048576, unsupportedParams: ["temperature", "top_p", "top_k"] },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5", contextLength: 1048576, unsupportedParams: ["temperature", "top_p", "top_k"] },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
  ],
  passthroughModels: true,
  serviceKinds: ["llm", "imageToText"],
};
