const modelIds = [
  "anthropic/claude-4-opus",
  "anthropic/claude-4-sonnet",
  "openai/gpt-oss-120b",
  "openai/gpt-oss-20b",
  "google/gemma-4-31B-it",
  "google/gemma-4-26B-A4B-it",
  "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B",
  "nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning",
  "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
  "meta-llama/Llama-4-Scout-17B-16E-Instruct",
  "meta-llama/Llama-3.3-70B-Instruct-Turbo",
  "NousResearch/Hermes-3-Llama-3.1-405B",
  "deepseek-ai/DeepSeek-V4-Pro",
  "deepseek-ai/DeepSeek-V4-Flash",
  "zai-org/GLM-5.1",
  "moonshotai/Kimi-K2.6",
  "MiniMaxAI/MiniMax-M2.5",
  "Qwen/Qwen3.6-35B-A3B",
  "Qwen/Qwen3.5-397B-A17B",
  "Qwen/Qwen3.5-122B-A10B",
  "XiaomiMiMo/MiMo-V2.5-Pro",
  "XiaomiMiMo/MiMo-V2.5",
];

export default {
  id: "deepinfra",
  alias: "deepinfra",
  category: "freeTier",
  hasFree: true,
  authType: "apikey",
  display: {
    name: "DeepInfra",
    icon: "hub",
    color: "#2563EB",
    textIcon: "DI",
    website: "https://deepinfra.com",
  },
  transport: { baseUrl: "https://api.deepinfra.com/v1/openai/chat/completions" },
  models: modelIds.map((id) => ({ id, name: id })),
};
