export default {
  id: "genspark",
  alias: "genspark",
  aliases: ["genspark-ai", "gsk"],
  uiAlias: "gsk",
  display: {
    name: "Genspark",
    icon: "auto_awesome",
    color: "#F97316",
    textIcon: "GS",
    website: "https://www.genspark.ai",
    notice: {
      text: "Genspark API access. Use an API key issued by your Genspark account.",
      apiKeyUrl: "https://www.genspark.ai",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://www.genspark.ai/api/llm_proxy/v1/chat/completions",
    auth: { combined: true, header: "Authorization", scheme: "bearer" },
    thinkingFormat: "openai",
  },
  modelsFetcher: {
    url: "https://www.genspark.ai/api/llm_proxy/v1/models",
    type: "openai",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
  },
  // Fallback catalog; the live /v1/models response replaces this list when available.
  models: [
    ["claude-fable-5", "Claude Fable 5"], ["claude-opus-5-5", "Claude Opus 5.5"], ["claude-opus-5", "Claude Opus 5"],
    ["claude-opus-4-8", "Claude Opus 4.8"], ["claude-opus-4-7", "Claude Opus 4.7"],
    ["claude-opus-4-6-1m", "Claude Opus 4.6 (1M)"], ["claude-sonnet-4-6-1m", "Claude Sonnet 4.6 (1M)"],
    ["claude-opus-4-6", "Claude Opus 4.6"], ["claude-sonnet-5", "Claude Sonnet 5"],
    ["claude-sonnet-4-6", "Claude Sonnet 4.6"], ["claude-haiku-4-5", "Claude Haiku 4.5"],
    ["gpt-5.2", "GPT-5.2"], ["gpt-5.4", "GPT-5.4"], ["gpt-5.5", "GPT-5.5"],
    ["gpt-6-astra", "GPT-6 Astra"], ["gpt-6-sol", "GPT-6 Sol"], ["gpt-6-luna", "GPT-6 Luna"],
    ["gpt-5.6-sol", "GPT-5.6 Sol"], ["gpt-5.6-terra", "GPT-5.6 Terra"], ["gpt-5.6-luna", "GPT-5.6 Luna"],
    ["deep-seek-v4-pro-baseten", "DeepSeek V4 Pro (Baseten)"], ["deep-seek-v4-flash", "DeepSeek V4 Flash"],
    ["gpt-5.4-mini", "GPT-5.4 Mini"], ["gpt-5.4-nano", "GPT-5.4 Nano"],
    ["grok-4.5", "Grok 4.5"], ["grok-4.6", "Grok 4.6"], ["grok-4.7", "Grok 4.7"], ["kimi-k2p6", "Kimi K2.6"],
    ["minimax-m2p7", "MiniMax M2.7"], ["minimax-m3", "MiniMax M3"], ["glm-5p2", "GLM-5.2"],
    ["kimi-k3", "Kimi K3"], ["deepseek-v4-pro-0813", "DeepSeek V4 Pro 0813"], ["solar-pro4", "Solar Pro 4"],
    ["gemini-3.1-pro-preview", "Gemini 3.1 Pro Preview"], ["gemini-3-flash-preview", "Gemini 3 Flash Preview"],
    ["gemini-3.5-flash", "Gemini 3.5 Flash"], ["gemini-3.6-flash", "Gemini 3.6 Flash"],
    ["gemini-3.7-flash", "Gemini 3.7 Flash"], ["gemini-3.1-flash-lite-preview", "Gemini 3.1 Flash Lite Preview"],
  ].map(([id, name]) => ({ id, name })),
  passthroughModels: true,
  serviceKinds: ["llm"],
};
