export default {
  id: "gorouter",
  priority: 16,
  alias: "gorouter",
  aliases: ["gr", "gorouter-app"],
  uiAlias: "gr",
  hasFree: true,
  display: {
    name: "GoRouter",
    icon: "router",
    color: "#6366F1",
    textIcon: "GR",
    website: "https://gorouter.app",
    notice: {
      text: "Fast AI routing gateway for OpenAI, Claude, Gemini, DeepSeek, and open models.",
      apiKeyUrl: "https://gorouter.app/sign",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.gorouter.app/v1/chat/completions",
    validateUrl: "https://api.gorouter.app/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    { id: "gorouter/auto:free", name: "GoRouter Auto (Free)", isFreeTier: true },
    { id: "deepseek/deepseek-r1:free", name: "DeepSeek R1 (Free)", supportsReasoning: true, isFreeTier: true },
    { id: "deepseek/deepseek-chat:free", name: "DeepSeek V3 (Free)", isFreeTier: true },
    { id: "meta-llama/llama-3.3-70b-instruct:free", name: "Llama 3.3 70B (Free)", isFreeTier: true },
    { id: "qwen/qwen-2.5-coder-32b-instruct:free", name: "Qwen 2.5 Coder 32B (Free)", isFreeTier: true },
    { id: "openai/gpt-4o-mini:free", name: "GPT-4o Mini (Free)", isFreeTier: true },
    { id: "claude-3-7-sonnet", name: "Claude 3.7 Sonnet" },
    { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "deepseek-chat", name: "DeepSeek V3" },
    { id: "deepseek-reasoner", name: "DeepSeek R1", supportsReasoning: true },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
  ],
  passthroughModels: true,
  serviceKinds: ["llm"],
  defaultBaseUrl: "https://api.gorouter.app/v1",
  modelsFetcher: {
    url: "https://api.gorouter.app/v1/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
  },
};
