export default {
  id: "grok-web",
  priority: 150,
  alias: "grok-web",
  aliases: [
    "gw",
  ],
  uiAlias: "gw",
  display: {
    name: "Grok Web (Subscription)",
    icon: "auto_awesome",
    color: "#1DA1F2",
    textIcon: "GW",
    website: "https://grok.com",
  },
  category: "webCookie",
  authType: "cookie",
  authHint: "Paste your full Cookie header from grok.com (or at least the sso= and sso-rw= cookie values). cf_clearance/__cf_bm are forwarded when present but only work with the exact same User-Agent as the browser, from the same IP, and through a proxy that preserves the TLS fingerprint.",
  transport: {
    baseUrl: "https://grok.com/rest/app-chat/conversations/new",
    format: "grok-web",
    authType: "cookie",
  },
  models: [
    { id: "grok-3", name: "Grok 3" },
    { id: "grok-3-mini", name: "Grok 3 Mini (Thinking)" },
    { id: "grok-3-thinking", name: "Grok 3 Thinking" },
    { id: "grok-4", name: "Grok 4" },
    { id: "grok-4-mini", name: "Grok 4 Mini (Thinking)" },
    { id: "grok-4-thinking", name: "Grok 4 Thinking" },
    { id: "grok-4-heavy", name: "Grok 4 Heavy (SuperGrok)" },
    { id: "grok-4.1-mini", name: "Grok 4.1 Mini (Thinking)" },
    { id: "grok-4.1-fast", name: "Grok 4.1 Fast" },
    { id: "grok-4.1-expert", name: "Grok 4.1 Expert" },
    { id: "grok-4.1-thinking", name: "Grok 4.1 Thinking" },
    { id: "grok-4.2", name: "Grok 4.2 (4.20 Beta)" },
  ],
  passthroughModels: true,
};
