export default {
  id: "mistral",
  priority: 80,
  alias: "mistral",
  display: {
    name: "Mistral",
    icon: "air",
    color: "#FF7000",
    textIcon: "MI",
    website: "https://mistral.ai",
    notice: {
      apiKeyUrl: "https://console.mistral.ai/api-keys",
    },
  },
  category: "apikey",
  hasFree: true,
  transport: {
    baseUrl: "https://api.mistral.ai/v1/chat/completions",
    validateUrl: "https://api.mistral.ai/v1/models",
    quirks: {
      dropClientMetadata: true,
    },
  },
  models: [
    { id: "mistral-large-latest", name: "Mistral Large 3" },
    { id: "mistral-medium-latest", name: "Mistral Medium 3.5" },
    { id: "mistral-small-latest", name: "Mistral Small 4" },
    { id: "mistral-small-2603", name: "Mistral Small 2603" },
    { id: "magistral-medium-latest", name: "Magistral Medium 1.2", supportsReasoning: true },
    { id: "codestral-latest", name: "Codestral (Latest)" },
    { id: "codestral-2501", name: "Codestral 25.01" },
    { id: "devstral-latest", name: "Devstral 2" },
    { id: "devstral-2512", name: "Devstral 2512" },
    { id: "pixtral-large-latest", name: "Pixtral Large", supportsVision: true },
    { id: "pixtral-12b", name: "Pixtral 12B", supportsVision: true },
    { id: "voxtral-small-latest", name: "Voxtral Small" },
    { id: "ministral-14b-latest", name: "Ministral 3 14B" },
    { id: "ministral-8b-latest", name: "Ministral 3 8B", isFreeTier: true },
    { id: "ministral-3b-latest", name: "Ministral 3 3B", isFreeTier: true },
    { id: "mistral-embed", name: "Mistral Embed", kind: "embedding" },
    { id: "codestral-embed", name: "Codestral Embed", kind: "embedding" },
  ],
  passthroughModels: true,
  serviceKinds: ["llm","imageToText","embedding"],
  embeddingConfig: { baseUrl: "https://api.mistral.ai/v1/embeddings", authType: "apikey", authHeader: "bearer" },
};
