export default {
  id: "notion-web",
  priority: 150,
  alias: "nw",
  aliases: ["nw", "notion-web", "notionai"],
  uiAlias: "nw",
  display: {
    name: "Notion AI (Web)",
    icon: "bolt",
    color: "#1A1A1A",
    textIcon: "N",
    website: "https://app.notion.com",
  },
  category: "webCookie",
  authType: "cookie",
  authHint:
    "EXPERIMENTAL — unofficial Notion AI bridge over an undocumented internal endpoint; can break when Notion changes its web client. Paste your token_v2 cookie from app.notion.com (DevTools → Application → Cookies). token_v2 alone usually suffices; add space_id and notion_browser_id only if a request needs them. Avoid pasting your full Cookie header: every extra cookie widens exposure if this credential ever leaks.",
  transport: {
    baseUrl: "https://app.notion.com/api/v3/runInferenceTranscript",
    format: "openai",
    authType: "cookie",
  },
  // Seed list only — the executor accepts any friendly slug / food codename via
  // its static mapping (see executors/notion-web.js). passthroughModels forwards
  // the client model id untouched.
  models: [
    { id: "notion-ai", name: "Notion AI (default)" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gpt-5.6-luna", name: "GPT-5.6 Luna" },
    { id: "gpt-5.2", name: "GPT-5.2" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "gpt-5.4-nano", name: "GPT-5.4 Nano" },
    { id: "sonnet-5", name: "Sonnet 5" },
    { id: "sonnet-4.6", name: "Sonnet 4.6" },
    { id: "opus-4.7", name: "Opus 4.7" },
    { id: "opus-4.8", name: "Opus 4.8" },
    { id: "opus-4.6", name: "Opus 4.6" },
    { id: "haiku-4.5", name: "Haiku 4.5" },
    { id: "fable-5", name: "Fable 5" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "gemini-3-flash", name: "Gemini 3 Flash" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "grok-4.5", name: "Grok 4.5" },
    { id: "grok-4.3", name: "Grok 4.3" },
    { id: "grok-build-0.1", name: "Grok Build 0.1" },
  ],
  passthroughModels: true,
};
