export default {
  id: "openagentic",
  priority: 19,
  alias: "openagentic",
  aliases: ["oa", "openagentic-ai"],
  uiAlias: "oa",
  hasFree: true,
  display: {
    name: "OpenAgentic",
    icon: "hub",
    color: "#EC4899",
    textIcon: "OA",
    website: "https://openagentic.ai",
    notice: {
      text: "Open AI Agent marketplace & model orchestration platform.",
      apiKeyUrl: "https://openagentic.ai",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.openagentic.ai/v1/chat/completions",
    validateUrl: "https://api.openagentic.ai/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    { id: "openagentic/auto:free", name: "OpenAgentic Auto (Free)", isFreeTier: true },
    { id: "claude-3-7-sonnet", name: "Claude 3.7 Sonnet" },
    { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "deepseek-chat", name: "DeepSeek V3" },
    { id: "deepseek-reasoner", name: "DeepSeek R1", supportsReasoning: true },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
  ],
  passthroughModels: true,
  serviceKinds: ["llm"],
  defaultBaseUrl: "https://api.openagentic.ai/v1",
  modelsFetcher: {
    url: "https://api.openagentic.ai/v1/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
  },
};
