export default {
  id: "qoder",
  priority: 30,
  alias: "qd",
  uiAlias: "qd",
  display: {
    name: "Qoder",
    icon: "water_drop",
    color: "#EC4899",
    website: "https://qoder.com",
    notice: {
      signupUrl: "https://qoder.com",
    },
  },
  category: "oauth",
  authModes: ["oauth", "apikey"],
  hasOAuth: true,
  authHint: "Personal Access Token (pt-...) từ https://qoder.com/account/integrations",
  transport: {
    baseUrl: "https://api3.qoder.sh/algo/api/v2/service/pro/sse/agent_chat_generation",
    headers: {},
    timeoutMs: 120000,
    stallTimeoutMs: 120000,
    usage: {
      url: "https://openapi.qoder.sh/api/v2/quota/usage",
    },
  },
  models: [{
  id: "ultimate",
  name: "Ultimate"
}, {
  id: "auto",
  name: "Auto"
}, {
  id: "performance",
  name: "Performance"
}, {
  id: "efficient",
  name: "Efficient"
}, {
  id: "qmodel_preview",
  name: "Qwen3.8-Max-Preview"
}, {
  id: "qmodel_latest",
  name: "Qwen3.7-Max"
}, {
  id: "qmodel",
  name: "Qwen3.7-Plus"
}, {
  id: "kmodel_latest",
  name: "Kimi-K3"
}, {
  id: "kmodel",
  name: "Kimi-K2.7-Code"
}, {
  id: "gm51model",
  name: "GLM-5.2"
}, {
  id: "dmodel",
  name: "DeepSeek-V4-Pro"
}, {
  id: "dfmodel",
  name: "DeepSeek-V4-Flash"
}, {
  id: "mmodel",
  name: "MiniMax-M3"
}, {
  "id": "qwen3.8-max-preview",
  "name": "Qwen3.8-Max-Preview",
  "supportsVision": true,
  "supportsReasoning": true,
  "contextLength": 1000000,
  "maxInputTokens": 180000
}, {
  "id": "qwen3.7-max",
  "name": "Qwen3.7-Max",
  "supportsVision": true,
  "contextLength": 1000000
}, {
  "id": "qwen3.7-plus",
  "name": "Qwen3.7-Plus",
  "supportsVision": true,
  "contextLength": 1000000
}, {
  "id": "kimi-k3",
  "name": "Kimi-K3",
  "supportsVision": true,
  "contextLength": 1000000,
  "maxInputTokens": 180000
}, {
  "id": "kimi-k2.7-code",
  "name": "Kimi-K2.7-Code",
  "supportsVision": true,
  "contextLength": 256000
}, {
  "id": "glm-5.2",
  "name": "GLM-5.2",
  "supportsVision": true,
  "supportsReasoning": true,
  "contextLength": 1000000
}, {
  "id": "deepseek-v4-pro",
  "name": "DeepSeek-V4-Pro",
  "supportsVision": true,
  "supportsReasoning": true,
  "contextLength": 1000000
}, {
  "id": "deepseek-v4-flash",
  "name": "DeepSeek-V4-Flash",
  "supportsVision": true,
  "supportsReasoning": true,
  "contextLength": 1000000
}, {
  "id": "minimax-m3",
  "name": "MiniMax-M3",
  "supportsVision": true,
  "contextLength": 1000000
}],
  oauth: {
    openApiBaseUrl: "https://openapi.qoder.sh",
    centerBaseUrl: "https://center.qoder.sh",
    chatBaseUrl: "https://api3.qoder.sh",
    deviceTokenUrl: "https://openapi.qoder.sh/api/v1/deviceToken/poll",
    refreshUrl: "https://center.qoder.sh/algo/api/v3/user/refresh_token",
    userInfoUrl: "https://openapi.qoder.sh/api/v1/userinfo",
    quotaUsageUrl: "https://openapi.qoder.sh/api/v2/quota/usage",
    loginUrl: "https://qoder.com/device/selectAccounts",
  },
  features: {
    usage: true,
    // PAT (apikey) connections also carry quota usage (via job-token exchange).
    usageApikey: true,
  },
};
