export default {
  id: "sambanova",
  alias: "samba",
  aliases: ["sambanova-ai"],
  uiAlias: "samba",
  category: "freeTier",
  hasFree: true,
  display: {
    name: "SambaNova",
    icon: "memory",
    color: "#F97316",
    textIcon: "SN",
    website: "https://sambanova.ai",
    notice: {
      apiKeyUrl: "https://cloud.sambanova.ai/apis",
    },
  },
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.sambanova.ai/v1/chat/completions",
    validateUrl: "https://api.sambanova.ai/v1/models",
  },
  models: [
    { id: "DeepSeek-R1", name: "DeepSeek R1", supportsReasoning: true },
    { id: "DeepSeek-V3.2", name: "DeepSeek V3.2" },
    { id: "Meta-Llama-3.1-405B-Instruct", name: "Llama 3.1 405B Instruct" },
    { id: "Meta-Llama-3.3-70B-Instruct", name: "Llama 3.3 70B Instruct" },
    { id: "Llama-4-Maverick-17B-128E-Instruct", name: "Llama 4 Maverick" },
    { id: "Qwen2.5-Coder-32B-Instruct", name: "Qwen 2.5 Coder 32B" },
    { id: "Qwen2.5-72B-Instruct", name: "Qwen 2.5 72B" },
    { id: "MiniMax-M2.7", name: "MiniMax M2.7", contextLength: 196608 },
    { id: "gpt-oss-120b", name: "GPT OSS 120B" },
  ],
  passthroughModels: true,
};
