export default {
  id: "tabitoken",
  priority: 17,
  alias: "tabitoken",
  aliases: ["tabi", "tabitoken-app"],
  uiAlias: "tabi",
  hasFree: true,
  display: {
    name: "TabiToken",
    icon: "generating_tokens",
    color: "#10B981",
    textIcon: "TB",
    website: "https://tabitoken.com",
    notice: {
      text: "Unified AI API gateway & model routing with promotional trial credits.",
      apiKeyUrl: "https://tabitoken.com/sign",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.tabitoken.com/v1/chat/completions",
    validateUrl: "https://api.tabitoken.com/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    { id: "tabitoken/auto:free", name: "TabiToken Auto (Free)", isFreeTier: true },
    { id: "claude-3-7-sonnet", name: "Claude 3.7 Sonnet" },
    { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet" },
    { id: "claude-3-opus", name: "Claude 3 Opus" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "deepseek-chat", name: "DeepSeek V3" },
    { id: "deepseek-reasoner", name: "DeepSeek R1", supportsReasoning: true },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
  ],
  passthroughModels: true,
  serviceKinds: ["llm"],
  defaultBaseUrl: "https://api.tabitoken.com/v1",
  modelsFetcher: {
    url: "https://api.tabitoken.com/v1/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
  },
};
