export default {
  id: "unikey",
  priority: 18,
  alias: "unikey",
  aliases: ["getunikey", "unikey-ai"],
  uiAlias: "uk",
  hasFree: true,
  display: {
    name: "UniKey",
    icon: "vpn_key",
    color: "#8B5CF6",
    textIcon: "UK",
    website: "https://www.getunikey.ai",
    notice: {
      text: "Universal AI API gateway connecting major frontier and open models.",
      apiKeyUrl: "https://www.getunikey.ai",
    },
  },
  category: "freeTier",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.getunikey.ai/v1/chat/completions",
    validateUrl: "https://api.getunikey.ai/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    { id: "unikey/auto:free", name: "UniKey Auto (Free)", isFreeTier: true },
    { id: "claude-3-7-sonnet", name: "Claude 3.7 Sonnet" },
    { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "deepseek-chat", name: "DeepSeek V3" },
    { id: "deepseek-reasoner", name: "DeepSeek R1", supportsReasoning: true },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
  ],
  passthroughModels: true,
  serviceKinds: ["llm"],
  defaultBaseUrl: "https://api.getunikey.ai/v1",
  modelsFetcher: {
    url: "https://api.getunikey.ai/v1/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
  },
};
