export default {
  id: "xai",
  priority: 280,
  alias: "xai",
  display: {
    name: "xAI (Grok)",
    icon: "auto_awesome",
    color: "#1DA1F2",
    textIcon: "XA",
    website: "https://x.ai",
    notice: {
      apiKeyUrl: "https://console.x.ai",
    },
  },
  category: "oauth",
  authModes: [
    "oauth",
    "apikey",
  ],
  hasOAuth: true,
  thinkingConfig: {
    options: ["low", "medium", "high", "xhigh"],
    defaultMode: "high",
  },
  transport: {
    baseUrl: "https://api.x.ai/v1/chat/completions",
    validateUrl: "https://api.x.ai/v1/models",
    responsesUrl: "https://api.x.ai/v1/responses",
    clientId: "b1a00492-073a-47ea-816f-4c329264a828",
    tokenUrl: "https://auth.x.ai/oauth2/token",
    refreshUrl: "https://auth.x.ai/oauth2/token",
  },
  models: [
    { id: "grok-4.7", name: "Grok 4.7", contextLength: 500000, maxOutputTokens: 64000 },
    { id: "grok-4.7-latest", name: "Grok 4.7 Latest", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.7" },
    { id: "grok-4.7-xhigh", name: "Grok 4.7 (xhigh)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.7(xhigh)" },
    { id: "grok-4.7-high", name: "Grok 4.7 (High)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.7(high)" },
    { id: "grok-4.7-medium", name: "Grok 4.7 (Medium)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.7(medium)" },
    { id: "grok-4.7-low", name: "Grok 4.7 (Low)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.7(low)" },
    { id: "grok-4.6", name: "Grok 4.6", contextLength: 500000, maxOutputTokens: 64000 },
    { id: "grok-4.6-latest", name: "Grok 4.6 Latest", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.6" },
    { id: "grok-4.6-xhigh", name: "Grok 4.6 (xhigh)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.6(xhigh)" },
    { id: "grok-4.6-high", name: "Grok 4.6 (High)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.6(high)" },
    { id: "grok-4.6-medium", name: "Grok 4.6 (Medium)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.6(medium)" },
    { id: "grok-4.6-low", name: "Grok 4.6 (Low)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.6(low)" },
    { id: "grok-4.5", name: "Grok 4.5", contextLength: 500000, maxOutputTokens: 64000 },
    { id: "grok-4.5-latest", name: "Grok 4.5 Latest", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.5" },
    { id: "grok-4.5-high", name: "Grok 4.5 (High)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.5(high)" },
    { id: "grok-4.5-medium", name: "Grok 4.5 (Medium)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.5(medium)" },
    { id: "grok-4.5-low", name: "Grok 4.5 (Low)", contextLength: 500000, maxOutputTokens: 64000, upstreamModelId: "grok-4.5(low)" },
    { id: "grok-4.3", name: "Grok 4.3", contextLength: 1000000 },
    { id: "grok-4.3-latest", name: "Grok 4.3 Latest", contextLength: 1000000, upstreamModelId: "grok-4.3" },
    { id: "grok-4.3-xhigh", name: "Grok 4.3 (xhigh)", contextLength: 1000000, upstreamModelId: "grok-4.3(xhigh)" },
    { id: "grok-4.3-high", name: "Grok 4.3 (High)", contextLength: 1000000, upstreamModelId: "grok-4.3(high)" },
    { id: "grok-4.3-medium", name: "Grok 4.3 (Medium)", contextLength: 1000000, upstreamModelId: "grok-4.3(medium)" },
    { id: "grok-4.3-low", name: "Grok 4.3 (Low)", contextLength: 1000000, upstreamModelId: "grok-4.3(low)" },
    { id: "grok-4.20-0309-reasoning", name: "Grok 4.20 Reasoning", contextLength: 1000000 },
    { id: "grok-4.20-reasoning", name: "Grok 4.20 Reasoning (alias)", contextLength: 1000000, upstreamModelId: "grok-4.20-0309-reasoning" },
    { id: "grok-4.20", name: "Grok 4.20", contextLength: 1000000, upstreamModelId: "grok-4.20-0309-reasoning" },
    { id: "grok-4.20-0309-non-reasoning", name: "Grok 4.20 Non-Reasoning", contextLength: 1000000 },
    { id: "grok-4.20-non-reasoning", name: "Grok 4.20 Non-Reasoning (alias)", contextLength: 1000000, upstreamModelId: "grok-4.20-0309-non-reasoning" },
    { id: "grok-4.20-multi-agent-0309", name: "Grok 4.20 Multi-Agent", contextLength: 1000000 },
    { id: "grok-4", name: "Grok 4" },
    { id: "grok-4-fast-reasoning", name: "Grok 4 Fast Reasoning" },
    { id: "grok-code-fast-1", name: "Grok Code Fast" },
    { id: "grok-3", name: "Grok 3" },
    { id: "grok-2-1212", name: "Grok 2" },
    { id: "grok-2-vision-1212", name: "Grok 2 Vision" },
    { id: "grok-beta", name: "Grok Beta" },
    { id: "grok-vision-beta", name: "Grok Vision Beta" },
    { id: "grok-build-0.1", name: "Grok Build 0.1", contextLength: 256000 },
    { id: "grok-2-image-1212", name: "Grok 2 Image", params: ["n", "response_format"], kind: "image" },
    { id: "grok-imagine-image", name: "Grok Imagine Image", params: ["n", "response_format"], kind: "image" },
    { id: "grok-imagine-image-2.0", name: "Grok Imagine Image 2.0", params: ["n", "response_format"], kind: "image" },
    { id: "grok-imagine-video", name: "Grok Imagine Video", params: ["duration", "aspect_ratio", "resolution"], kind: "video" },
    { id: "grok-imagine-video-1.5", name: "Grok Imagine Video 1.5", params: ["duration", "aspect_ratio", "resolution"], kind: "video" },
  ],
  hasFree: true,
  passthroughModels: true,
  serviceKinds: ["llm", "imageToText", "webSearch", "image", "video"],
  imageConfig: { baseUrl: "https://api.x.ai/v1/images/generations", bodyFields: ["model", "prompt", "n", "response_format"] },
  // Async video jobs (POST returns { request_id }, GET polls until done/failed).
  // Docs: https://docs.x.ai/developers/rest-api-reference/inference/videos
  videoConfig: { baseUrl: "https://api.x.ai/v1/videos" },
  searchViaChat: {
    defaultModel: "grok-4.7",
    endpoint: "https://api.x.ai/v1/responses",
    pricingUrl: "https://x.ai/api#pricing",
  },
};
